version: 2
updates:
  # ğŸ’¡ npm ä¾èµ–æ›´æ–°
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps(npm)'
    labels:
      - dependencies
      - npm

  # ğŸ’¡ GitHub Actions æ›´æ–°
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'ci(actions)'
    labels:
      - dependencies
      - github-actions
